### get all houses
get http://localhost:3000/houses

### get house by id
get http://localhost:3000/houses/3

### delete house by id
DELETE http://localhost:3000/houses/6

### post house
post http://localhost:3000/houses
Content-Type: application/json

{
    "ID": 6,
    "saleID": 1,
    "typeID": 6,
    "Settlement": "Salgótarján",
    "countyID": 5,
    "Rooms": 3,
    "parcelNumber": "95-57441-0135",
    "Area": 187,
    "Price": 42500000
}

### put a house
put http://localhost:3000/houses/6
Content-Type: application/json

{
    "ID": 6,
    "saleID": 1,
    "typeID": 6,
    "Settlement": "Salgótarján",
    "countyID": 5,
    "Rooms": 3,
    "parcelNumber": "95-57441-0135",
    "Area": 187,
    "Price": 42500000
}